version: "3.2"
services:
  db:
    build: db
    environment:
      - MYSQL_ROOT_PASSWORD=my-secret-pw
      - MYSQL_DATABASE=cenicienta
      - MYSQL_USER=cenicienta
      - MYSQL_PASSWORD=cenicienta
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - aguacate-demo
  swagger:
    image: swaggerapi/swagger-ui:latest
    ports:
      - "18080:8080"
    environment:
      - URL=http://localhost:18081/colorante.yaml
    depends_on:
      - aguacate
    networks:
      - aguacate-demo
  aguacate:
    build: services
    ports:
      - "18081:8080"
    depends_on:
      - db
    networks:
      - aguacate-demo
volumes:
  db-data:
networks:
  aguacate-demo:
