version: "3.7"
services:
  db:
    build: mariadb-demo
    environment:
      - MYSQL_ROOT_PASSWORD=my-secret-pw
      - MYSQL_DATABASE=cenicienta
      - MYSQL_USER=cenicienta
      - MYSQL_PASSWORD=cenicienta
    volumes:
      - db-data:/var/lib/mysql
  swagger:
    image: swaggerapi/swagger-ui:latest
    ports:
      - "8080:8080"
    environment:
      - URL=http://aguacate:8080/colorante.yaml
    depends_on:
      - aguacate
  aguacate:
    build: aguacate-swagger-demo
    ports:
      - "8081:8080"
    depends_on:
      - db
volumes:
  db-data:
