FROM razzek/aguacate-swagger:latest

COPY database/* /var/lib/aguacate/database/
COPY script/* /var/lib/aguacate/script/
COPY configuration/* /var/lib/aguacate/configuration/
COPY swagger/* /var/lib/aguacate/swagger/
